/**
 * Notification System Types
 * 
 * Based on the detailed specification for CampusConnect notifications
 */

export type NotificationType =
    | "follow"
    | "club_invite"
    | "club_join_request"
    | "post_like"
    | "comment_like"
    | "comment_reply"
    | "post_comment"
    | "announcement"
    | "system";

export interface NotificationDeeplink {
    screen: string;
    params: Record<string, any>;
}

export interface NotificationPush {
    send: boolean;
    status?: "pending" | "sent" | "skipped" | "failed";
    sentAt?: Date | null;
    error?: string | null;
}

export interface Notification {
    // ID (auto-generated by Firestore)
    id: string;

    // Recipient
    toUid: string;

    // Context (optional)
    campusId?: string | null;
    clubId?: string | null;
    postId?: string | null;
    commentId?: string | null;

    // Type
    type: NotificationType;

    // Content
    title: string;
    body?: string | null;
    imageUrl?: string | null;

    // Actor (who caused it)
    actorUid?: string | null;
    actorName?: string | null;
    actorPhotoURL?: string | null;

    // Navigation
    deeplink: NotificationDeeplink;

    // State
    createdAt: Date;
    isRead: boolean;
    readAt?: Date | null;
    seenAt?: Date | null;
    isArchived?: boolean;

    // Dedupe / grouping
    dedupeKey?: string | null;
    groupKey?: string | null;
    groupCount?: number | null;

    // Push metadata
    push: NotificationPush;

    // Version
    version: 1;
}

export interface DeviceToken {
    fcmToken: string;
    platform: "web" | "ios" | "android";
    deviceName: string;
    createdAt: Date;
    lastSeenAt: Date;
    userAgent?: string;
    disabled?: boolean;
    lastError?: string | null;
}

export interface NotificationPreferences {
    pushEnabled: boolean;
    pushTypes: Record<NotificationType, boolean>;
    quietHours?: {
        start: string;
        end: string;
        tz: string;
    };
}
